name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o
          PROMPT: |
            As an experienced React developer, review the following code diff for a React application. Analyze both the removed (-) and added (+) lines. Focus on:

            1. Impact on component structure and organization
            2. Changes in state management and hooks usage
            3. Performance implications
            4. Adherence to React best practices
            5. Code readability and maintainability improvements or regressions
            6. Changes in error handling and edge case coverage
            7. Accessibility improvements or regressions
            8. Effects on responsive design
            9. Implications for testing coverage and quality
            10. Security considerations

            For each significant change:
            - Explain the purpose and potential impact
            - Suggest improvements if necessary
            - Highlight good practices introduced
            - Identify any potential bugs or code smells
            - Provide specific refactoring suggestions where applicable

            Be concise but thorough. Prioritize the most important findings.
          top_p: 1
          temperature: 1
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000
